const RESPONSE_CONSTANTS = {
    OK_CODE: 200,
    NO_CONTENT_CODE: 204,
    BAD_REQUEST_CODE: 400,
    INTERNAL_ERROR_CODE: 500,
    BAD_REQUEST_MESSAGE: 'Bad Request',
    INTERNAL_ERROR_MESSAGE: 'Internal Server Error',
}

export { RESPONSE_CONSTANTS }
